<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>MarketAssistant</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);MAAI001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarketAssistant.Core\MarketAssistant.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
    <PackageReference Include="Microsoft.ML.Tokenizers" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.SqliteVec" />
    <PackageReference Include="Microsoft.SemanticKernel.Plugins.Web" />
    <PackageReference Include="PdfPig" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>
</Project>
