name: 功能请求
description: 提出一个新功能或改进建议
labels: [enhancement]
title: "feat: [简要标题]"
body:
  - type: textarea
    id: motivation
    attributes:
      label: 需求动机
      description: 为什么需要该功能？解决了什么问题？
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 期望的解决方案
      description: 你设想的实现方式或验收标准
  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案或权衡
  - type: textarea
    id: context
    attributes:
      label: 额外上下文
      description: 相关截图、链接、参考资料


