# 支持的AI模型配置
models:
  - Qwen/Qwen3-32B
  - Qwen/Qwen3-235B-A22B
  - Tongyi-Zhiwen/QwenLong-L1-32B
  - deepseek-ai/DeepSeek-R1
  - deepseek-ai/DeepSeek-V3.1
  - zai-org/GLM-4.5
  - zai-org/GLM-4.5-Air
  - moonshotai/Kimi-K2-Instruct
