# 支持的AI模型配置
models:
  - Tongyi-Zhiwen/QwenLong-L1-32B
  - Qwen/Qwen3-32B
  - Qwen/Qwen3-235B-A22B
  - deepseek-ai/DeepSeek-R1
  - deepseek-ai/DeepSeek-V3
  - THUDM/GLM-4-32B-0414
  - THUDM/GLM-Z1-Rumination-32B-0414
  - tencent/Hunyuan-A13B-Instruct
  - baidu/ERNIE-4.5-300B-A47B